stages:
  - build
  - deploy

build:
  image: node:latest    # Run the job in a `node` docker image
  stage: build
  script:
    - yarn install      # Run `yarn install` and `yarn build`
    - yarn build
  artifacts:
    paths:
      - build/        # Save the build result as an artfact
  only:
    - main
    - /^.*-deploy$/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
    - apk add --update --no-cache python3
    - ln -sf python3 /usr/bin/python
    - python3 -m ensurepip
    - pip3 install --upgrade pip
    - ls -la
    - pip3 install -r flask/requirements.txt
    - python3 flask/app.py &
  artifacts:
    paths:
      - public
  only:
    - main
    - /^.*-deploy$/