#!/bin/bash
# pyinstaller --onefile -w --name=testing app.py
cd app
title="Dog Vision"
package="dog_vision"
version=$1
# icon=$2
# splash=$3

buildozer init --y

# sed -i \
# -e "/\(icon.filename\).*/s/^#//g" \
# -e "/\(presplash.filename\).*/s/^#//g" \
# buildozer.spec

sed -i \
-e "s/\(title = \).*/\1$title/" \
-e "s/\(package.name = \).*/\1$package/" \
-e "s/\(version = \).*/\1$version/" \
buildozer.spec
# -e "s/\(icon.filename = \).*/\1$icon/" \
# -e "s/\(presplash.filename = \).*/\1$splash/" \

buildozer -v android debug deploy --y