services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'dogeye-test-db'
      MYSQL_ROOT_PASSWORD: 'password'
      ON_CREATE_DB: dogeye-test
    ports:
      # just if you also want to access it directly from you host
      # node neede for phpmyadmin
      - "3306:3306"

# login to phpmyadmin using Server: db, Username: root, Password: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1