services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mexigo/webapp
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    container_name: megico-webapp
  
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mexigo!root!pw
    container_name: megico-db
